FROM ubuntu:22.04

# Installer Java 21
RUN apt-get update && apt-get install -y wget curl unzip python3 python3-pip openjdk-21-jdk bash coreutils \
    && rm -rf /var/lib/apt/lists/*

# Créer un lien python -> python3
RUN ln -sf /usr/bin/python3 /usr/bin/python

# Installer pytubefix
RUN pip install --no-cache-dir pytubefix